import type {
  LeagueRef,
  MatchDetail,
  MatchSummary,
  PlayerProfile,
  StandingRow,
} from "./types";

const leagues: Record<string, LeagueRef> = {
  pl: {
    id: "pl",
    name: "Premier League",
    country: "England",
    season: "2025/26",
  },
  laliga: {
    id: "laliga",
    name: "La Liga",
    country: "Spain",
    season: "2025/26",
  },
  ucl: {
    id: "ucl",
    name: "Champions League",
    country: "Europe",
    season: "2025/26",
  },
};

export function getMockLeagues(): LeagueRef[] {
  return Object.values(leagues);
}

const matchSummaries: MatchSummary[] = [
  {
    id: "m1",
    league: leagues.pl,
    home: {
      id: "t-ars",
      name: "Arsenal",
      shortName: "ARS",
      logo: "https://media.api-sports.io/football/teams/42.png",
    },
    away: {
      id: "t-che",
      name: "Chelsea",
      shortName: "CHE",
      logo: "https://media.api-sports.io/football/teams/49.png",
    },
    homeScore: 2,
    awayScore: 1,
    minute: "67'",
    status: "live",
    kickoff: new Date().toISOString(),
    venue: "Emirates Stadium",
  },
  {
    id: "m2",
    league: leagues.laliga,
    home: {
      id: "t-rma",
      name: "Real Madrid",
      shortName: "RMA",
      logo: "https://media.api-sports.io/football/teams/541.png",
    },
    away: {
      id: "t-bar",
      name: "Barcelona",
      shortName: "BAR",
      logo: "https://media.api-sports.io/football/teams/529.png",
    },
    homeScore: null,
    awayScore: null,
    minute: null,
    status: "scheduled",
    kickoff: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    venue: "Santiago Bernabéu",
  },
  {
    id: "m3",
    league: leagues.ucl,
    home: {
      id: "t-bay",
      name: "Bayern Munich",
      shortName: "BAY",
      logo: "https://media.api-sports.io/football/teams/157.png",
    },
    away: {
      id: "t-psg",
      name: "Paris SG",
      shortName: "PSG",
      logo: "https://media.api-sports.io/football/teams/85.png",
    },
    homeScore: 3,
    awayScore: 2,
    minute: null,
    status: "finished",
    kickoff: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    venue: "Allianz Arena",
  },
  {
    id: "m4",
    league: leagues.pl,
    home: {
      id: "t-liv",
      name: "Liverpool",
      shortName: "LIV",
      logo: "https://media.api-sports.io/football/teams/40.png",
    },
    away: {
      id: "t-mci",
      name: "Manchester City",
      shortName: "MCI",
      logo: "https://media.api-sports.io/football/teams/50.png",
    },
    homeScore: null,
    awayScore: null,
    minute: null,
    status: "scheduled",
    kickoff: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    venue: "Anfield",
  },
  {
    id: "m5",
    league: leagues.laliga,
    home: {
      id: "t-atm",
      name: "Atlético Madrid",
      shortName: "ATM",
      logo: "https://media.api-sports.io/football/teams/530.png",
    },
    away: {
      id: "t-sev",
      name: "Sevilla",
      shortName: "SEV",
      logo: "https://media.api-sports.io/football/teams/536.png",
    },
    homeScore: 1,
    awayScore: 0,
    minute: null,
    status: "finished",
    kickoff: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
    venue: "Cívitas Metropolitano",
  },
];

const details: Record<string, MatchDetail> = {
  m1: {
    ...matchSummaries[0],
    timeline: [
      {
        id: "e1",
        minute: "12'",
        type: "goal",
        team: "home",
        detail: "Goal",
        player: "Bukayo Saka",
        assist: "Martin Ødegaard",
      },
      {
        id: "e2",
        minute: "34'",
        type: "card",
        team: "away",
        detail: "Yellow card",
        player: "Enzo Fernández",
      },
      {
        id: "e3",
        minute: "41'",
        type: "goal",
        team: "away",
        detail: "Goal",
        player: "Nicolas Jackson",
      },
      {
        id: "e4",
        minute: "58'",
        type: "subst",
        team: "home",
        detail: "Substitution",
        player: "Gabriel Jesus → Leandro Trossard",
      },
      {
        id: "e5",
        minute: "63'",
        type: "goal",
        team: "home",
        detail: "Goal",
        player: "William Saliba",
      },
    ],
    lineups: {
      home: {
        formation: "4-3-3",
        starting: [
          { id: "p1", name: "Raya", number: 1, pos: "G" },
          { id: "p2", name: "White", number: 4, pos: "D" },
          { id: "p3", name: "Saliba", number: 12, pos: "D", isCaptain: true },
          { id: "p4", name: "Gabriel", number: 6, pos: "D" },
          { id: "p5", name: "Timber", number: 12, pos: "D" },
          { id: "p6", name: "Ødegaard", number: 8, pos: "M" },
          { id: "p7", name: "Rice", number: 41, pos: "M" },
          { id: "p8", name: "Havertz", number: 29, pos: "M" },
          { id: "p9", name: "Saka", number: 7, pos: "F" },
          { id: "p10", name: "Martinelli", number: 11, pos: "F" },
          { id: "p11", name: "Jesus", number: 9, pos: "F" },
        ],
        substitutes: [
          { id: "p12", name: "Trossard", number: 19, pos: "F" },
          { id: "p13", name: "Jorginho", number: 20, pos: "M" },
          { id: "p14", name: "Kiwior", number: 15, pos: "D" },
        ],
      },
      away: {
        formation: "4-2-3-1",
        starting: [
          { id: "c1", name: "Sánchez", number: 1, pos: "G" },
          { id: "c2", name: "Gusto", number: 27, pos: "D" },
          { id: "c3", name: "Fofana", number: 29, pos: "D" },
          { id: "c4", name: "Colwill", number: 26, pos: "D" },
          { id: "c5", name: "Cucurella", number: 3, pos: "D" },
          { id: "c6", name: "Caicedo", number: 25, pos: "M" },
          { id: "c7", name: "Enzo", number: 8, pos: "M" },
          { id: "c8", name: "Palmer", number: 20, pos: "M" },
          { id: "c9", name: "Madueke", number: 11, pos: "M" },
          { id: "c10", name: "Sterling", number: 7, pos: "F" },
          { id: "c11", name: "Jackson", number: 15, pos: "F" },
        ],
        substitutes: [
          { id: "c12", name: "Petrović", number: 28, pos: "G" },
          { id: "c13", name: "Chilwell", number: 21, pos: "D" },
        ],
      },
    },
    stats: [
      { label: "Ball possession", home: 58, away: 42 },
      { label: "Total shots", home: 14, away: 9 },
      { label: "Shots on target", home: 6, away: 4 },
      { label: "Passes", home: 512, away: 389 },
      { label: "Pass accuracy %", home: 87, away: 82 },
      { label: "Fouls", home: 11, away: 14 },
      { label: "Corners", home: 7, away: 3 },
      { label: "Offsides", home: 2, away: 1 },
    ],
  },
  m2: {
    ...matchSummaries[1],
    timeline: [
      {
        id: "r1",
        minute: "0'",
        type: "period",
        team: "home",
        detail: "Match scheduled",
      },
    ],
    lineups: {
      home: {
        formation: "4-3-3",
        starting: Array.from({ length: 11 }, (_, i) => ({
          id: `rh${i}`,
          name: `Starter ${i + 1}`,
          number: i + 1,
          pos: i === 0 ? "G" : i < 5 ? "D" : i < 8 ? "M" : "F",
        })),
        substitutes: [],
      },
      away: {
        formation: "4-3-3",
        starting: Array.from({ length: 11 }, (_, i) => ({
          id: `ra${i}`,
          name: `Starter ${i + 1}`,
          number: i + 1,
          pos: i === 0 ? "G" : i < 5 ? "D" : i < 8 ? "M" : "F",
        })),
        substitutes: [],
      },
    },
    stats: [
      { label: "Ball possession", home: 50, away: 50 },
      { label: "Total shots", home: 0, away: 0 },
      { label: "Shots on target", home: 0, away: 0 },
      { label: "Passes", home: 0, away: 0 },
      { label: "Pass accuracy %", home: 0, away: 0 },
      { label: "Fouls", home: 0, away: 0 },
    ],
  },
};

function defaultDetail(summary: MatchSummary): MatchDetail {
  const base = details[summary.id];
  if (base) return base;
  return {
    ...summary,
    timeline: [
      {
        id: "x0",
        minute: "0'",
        type: "period",
        team: "home",
        detail: "Match info",
      },
    ],
    lineups: {
      home: { starting: [], substitutes: [] },
      away: { starting: [], substitutes: [] },
    },
    stats: [
      { label: "Ball possession", home: 50, away: 50 },
      { label: "Total shots", home: 0, away: 0 },
      { label: "Passes", home: 0, away: 0 },
      { label: "Fouls", home: 0, away: 0 },
    ],
  };
}

export function getMockMatches(): MatchSummary[] {
  return [...matchSummaries];
}

export function getMockMatchDetail(id: string): MatchDetail | null {
  const summary = matchSummaries.find((m) => m.id === id);
  if (!summary) return null;
  return defaultDetail(summary);
}

const standingsByLeague: Record<string, StandingRow[]> = {
  pl: [
    {
      rank: 1,
      team: {
        id: "t-ars",
        name: "Arsenal",
        logo: "https://media.api-sports.io/football/teams/42.png",
      },
      played: 28,
      won: 19,
      drawn: 4,
      lost: 5,
      goalsFor: 61,
      goalsAgainst: 28,
      points: 61,
      form: ["W", "W", "D", "W", "L"],
    },
    {
      rank: 2,
      team: {
        id: "t-liv",
        name: "Liverpool",
        logo: "https://media.api-sports.io/football/teams/40.png",
      },
      played: 28,
      won: 18,
      drawn: 5,
      lost: 5,
      goalsFor: 59,
      goalsAgainst: 30,
      points: 59,
      form: ["W", "D", "W", "W", "W"],
    },
    {
      rank: 3,
      team: {
        id: "t-mci",
        name: "Manchester City",
        logo: "https://media.api-sports.io/football/teams/50.png",
      },
      played: 28,
      won: 17,
      drawn: 6,
      lost: 5,
      goalsFor: 58,
      goalsAgainst: 32,
      points: 57,
      form: ["L", "W", "W", "D", "W"],
    },
    {
      rank: 4,
      team: {
        id: "t-che",
        name: "Chelsea",
        logo: "https://media.api-sports.io/football/teams/49.png",
      },
      played: 28,
      won: 14,
      drawn: 7,
      lost: 7,
      goalsFor: 48,
      goalsAgainst: 36,
      points: 49,
      form: ["W", "L", "D", "W", "W"],
    },
  ],
  laliga: [
    {
      rank: 1,
      team: {
        id: "t-bar",
        name: "Barcelona",
        logo: "https://media.api-sports.io/football/teams/529.png",
      },
      played: 27,
      won: 19,
      drawn: 3,
      lost: 5,
      goalsFor: 62,
      goalsAgainst: 24,
      points: 60,
      form: ["W", "W", "W", "D", "W"],
    },
    {
      rank: 2,
      team: {
        id: "t-rma",
        name: "Real Madrid",
        logo: "https://media.api-sports.io/football/teams/541.png",
      },
      played: 27,
      won: 18,
      drawn: 4,
      lost: 5,
      goalsFor: 58,
      goalsAgainst: 28,
      points: 58,
      form: ["W", "D", "W", "W", "L"],
    },
    {
      rank: 3,
      team: {
        id: "t-atm",
        name: "Atlético Madrid",
        logo: "https://media.api-sports.io/football/teams/530.png",
      },
      played: 27,
      won: 16,
      drawn: 8,
      lost: 3,
      goalsFor: 45,
      goalsAgainst: 22,
      points: 56,
      form: ["W", "W", "D", "D", "W"],
    },
  ],
  ucl: [
    {
      rank: 1,
      team: {
        id: "t-liv",
        name: "Liverpool",
        logo: "https://media.api-sports.io/football/teams/40.png",
      },
      played: 6,
      won: 5,
      drawn: 0,
      lost: 1,
      goalsFor: 14,
      goalsAgainst: 6,
      points: 15,
    },
    {
      rank: 2,
      team: {
        id: "t-bay",
        name: "Bayern Munich",
        logo: "https://media.api-sports.io/football/teams/157.png",
      },
      played: 6,
      won: 4,
      drawn: 1,
      lost: 1,
      goalsFor: 13,
      goalsAgainst: 5,
      points: 13,
    },
  ],
};

export function getMockStandings(leagueId: string): StandingRow[] {
  return standingsByLeague[leagueId] ?? standingsByLeague.pl;
}

const players: Record<string, PlayerProfile> = {
  "p-saka": {
    id: "p-saka",
    name: "Bukayo Saka",
    firstname: "Bukayo",
    lastname: "Saka",
    age: 23,
    nationality: "England",
    photo: "https://media.api-sports.io/football/players/1460.png",
    team: {
      id: "t-ars",
      name: "Arsenal",
      logo: "https://media.api-sports.io/football/teams/42.png",
    },
    position: "Right Winger",
    marketValue: "€140m",
    stats: {
      appearances: 26,
      goals: 12,
      assists: 8,
      minutes: 2210,
      rating: "7.42",
      yellowCards: 3,
      redCards: 0,
    },
  },
  "p-palmer": {
    id: "p-palmer",
    name: "Cole Palmer",
    firstname: "Cole",
    lastname: "Palmer",
    age: 22,
    nationality: "England",
    photo: "https://media.api-sports.io/football/players/152654.png",
    team: {
      id: "t-che",
      name: "Chelsea",
      logo: "https://media.api-sports.io/football/teams/49.png",
    },
    position: "Attacking Midfield",
    marketValue: "€90m",
    stats: {
      appearances: 27,
      goals: 14,
      assists: 6,
      minutes: 2345,
      rating: "7.38",
      yellowCards: 4,
      redCards: 0,
    },
  },
  "p-bellingham": {
    id: "p-bellingham",
    name: "Jude Bellingham",
    firstname: "Jude",
    lastname: "Bellingham",
    age: 21,
    nationality: "England",
    photo: "https://media.api-sports.io/football/players/998.png",
    team: {
      id: "t-rma",
      name: "Real Madrid",
      logo: "https://media.api-sports.io/football/teams/541.png",
    },
    position: "Midfielder",
    marketValue: "€180m",
    stats: {
      appearances: 24,
      goals: 11,
      assists: 4,
      minutes: 2050,
      rating: "7.55",
      yellowCards: 5,
      redCards: 0,
    },
  },
  "p-vinicius": {
    id: "p-vinicius",
    name: "Vinicius Junior",
    firstname: "Vinicius",
    lastname: "Junior",
    age: 25,
    nationality: "Brazil",
    photo: "https://media.api-sports.io/football/players/19527.png",
    team: { id: "t-rma", name: "Real Madrid", logo: "https://media.api-sports.io/football/teams/541.png" },
    position: "Left Winger",
    marketValue: "EUR 180m",
    stats: { appearances: 25, goals: 14, assists: 8, minutes: 2100, rating: "7.60", yellowCards: 4, redCards: 0 },
  },
  "p-mbappe": {
    id: "p-mbappe",
    name: "Kylian Mbappe",
    firstname: "Kylian",
    lastname: "Mbappe",
    age: 27,
    nationality: "France",
    photo: "https://media.api-sports.io/football/players/278.png",
    team: { id: "t-rma", name: "Real Madrid", logo: "https://media.api-sports.io/football/teams/541.png" },
    position: "Forward",
    marketValue: "EUR 180m",
    stats: { appearances: 26, goals: 21, assists: 6, minutes: 2200, rating: "7.75", yellowCards: 2, redCards: 0 },
  },
  "p-rodrygo": {
    id: "p-rodrygo",
    name: "Rodrygo",
    firstname: "Rodrygo",
    lastname: "Goes",
    age: 25,
    nationality: "Brazil",
    photo: "https://media.api-sports.io/football/players/19822.png",
    team: { id: "t-rma", name: "Real Madrid", logo: "https://media.api-sports.io/football/teams/541.png" },
    position: "Right Winger",
    marketValue: "EUR 100m",
    stats: { appearances: 27, goals: 12, assists: 7, minutes: 2180, rating: "7.30", yellowCards: 3, redCards: 0 },
  },
  "p-yamal": {
    id: "p-yamal",
    name: "Lamine Yamal",
    firstname: "Lamine",
    lastname: "Yamal",
    age: 19,
    nationality: "Spain",
    photo: "https://media.api-sports.io/football/players/170146.png",
    team: { id: "t-bar", name: "Barcelona", logo: "https://media.api-sports.io/football/teams/529.png" },
    position: "Right Winger",
    marketValue: "EUR 150m",
    stats: { appearances: 24, goals: 9, assists: 11, minutes: 1900, rating: "7.42", yellowCards: 2, redCards: 0 },
  },
  "p-lewandowski": {
    id: "p-lewandowski",
    name: "Robert Lewandowski",
    firstname: "Robert",
    lastname: "Lewandowski",
    age: 38,
    nationality: "Poland",
    photo: "https://media.api-sports.io/football/players/521.png",
    team: { id: "t-bar", name: "Barcelona", logo: "https://media.api-sports.io/football/teams/529.png" },
    position: "Striker",
    marketValue: "EUR 20m",
    stats: { appearances: 27, goals: 19, assists: 4, minutes: 2250, rating: "7.34", yellowCards: 4, redCards: 0 },
  },
  "p-pedri": {
    id: "p-pedri",
    name: "Pedri",
    firstname: "Pedro",
    lastname: "Gonzalez",
    age: 24,
    nationality: "Spain",
    photo: "https://media.api-sports.io/football/players/159599.png",
    team: { id: "t-bar", name: "Barcelona", logo: "https://media.api-sports.io/football/teams/529.png" },
    position: "Midfielder",
    marketValue: "EUR 100m",
    stats: { appearances: 22, goals: 5, assists: 7, minutes: 1680, rating: "7.20", yellowCards: 5, redCards: 0 },
  },
  "p-haaland": {
    id: "p-haaland",
    name: "Erling Haaland",
    firstname: "Erling",
    lastname: "Haaland",
    age: 26,
    nationality: "Norway",
    photo: "https://media.api-sports.io/football/players/1100.png",
    team: { id: "t-mci", name: "Manchester City", logo: "https://media.api-sports.io/football/teams/50.png" },
    position: "Striker",
    marketValue: "EUR 180m",
    stats: { appearances: 25, goals: 24, assists: 4, minutes: 2140, rating: "7.78", yellowCards: 2, redCards: 0 },
  },
  "p-debruyne": {
    id: "p-debruyne",
    name: "Kevin De Bruyne",
    firstname: "Kevin",
    lastname: "De Bruyne",
    age: 35,
    nationality: "Belgium",
    photo: "https://media.api-sports.io/football/players/272.png",
    team: { id: "t-mci", name: "Manchester City", logo: "https://media.api-sports.io/football/teams/50.png" },
    position: "Midfielder",
    marketValue: "EUR 50m",
    stats: { appearances: 20, goals: 6, assists: 12, minutes: 1490, rating: "7.61", yellowCards: 3, redCards: 0 },
  },
  "p-rodri": {
    id: "p-rodri",
    name: "Rodri",
    firstname: "Rodrigo",
    lastname: "Hernandez",
    age: 30,
    nationality: "Spain",
    photo: "https://media.api-sports.io/football/players/1117.png",
    team: { id: "t-mci", name: "Manchester City", logo: "https://media.api-sports.io/football/teams/50.png" },
    position: "Defensive Midfielder",
    marketValue: "EUR 120m",
    stats: { appearances: 28, goals: 8, assists: 7, minutes: 2430, rating: "7.50", yellowCards: 6, redCards: 0 },
  },
  "p-salah": {
    id: "p-salah",
    name: "Mohamed Salah",
    firstname: "Mohamed",
    lastname: "Salah",
    age: 34,
    nationality: "Egypt",
    photo: "https://media.api-sports.io/football/players/306.png",
    team: { id: "t-liv", name: "Liverpool", logo: "https://media.api-sports.io/football/teams/40.png" },
    position: "Right Winger",
    marketValue: "EUR 65m",
    stats: { appearances: 27, goals: 18, assists: 10, minutes: 2300, rating: "7.65", yellowCards: 3, redCards: 0 },
  },
  "p-van-dijk": {
    id: "p-van-dijk",
    name: "Virgil van Dijk",
    firstname: "Virgil",
    lastname: "van Dijk",
    age: 35,
    nationality: "Netherlands",
    photo: "https://media.api-sports.io/football/players/1884.png",
    team: { id: "t-liv", name: "Liverpool", logo: "https://media.api-sports.io/football/teams/40.png" },
    position: "Center Back",
    marketValue: "EUR 35m",
    stats: { appearances: 28, goals: 4, assists: 1, minutes: 2520, rating: "7.30", yellowCards: 5, redCards: 0 },
  },
  "p-palmer2": {
    id: "p-palmer2",
    name: "Cole Palmer",
    firstname: "Cole",
    lastname: "Palmer",
    age: 22,
    nationality: "England",
    photo: "https://media.api-sports.io/football/players/152654.png",
    team: { id: "t-che", name: "Chelsea", logo: "https://media.api-sports.io/football/teams/49.png" },
    position: "Attacking Midfield",
    marketValue: "EUR 100m",
    stats: { appearances: 27, goals: 14, assists: 6, minutes: 2345, rating: "7.38", yellowCards: 4, redCards: 0 },
  },
  "p-enzo": {
    id: "p-enzo",
    name: "Enzo Fernandez",
    firstname: "Enzo",
    lastname: "Fernandez",
    age: 25,
    nationality: "Argentina",
    photo: "https://media.api-sports.io/football/players/199000.png",
    team: { id: "t-che", name: "Chelsea", logo: "https://media.api-sports.io/football/teams/49.png" },
    position: "Midfielder",
    marketValue: "EUR 80m",
    stats: { appearances: 26, goals: 5, assists: 8, minutes: 2190, rating: "7.12", yellowCards: 7, redCards: 0 },
  },
  "p-rice": {
    id: "p-rice",
    name: "Declan Rice",
    firstname: "Declan",
    lastname: "Rice",
    age: 27,
    nationality: "England",
    photo: "https://media.api-sports.io/football/players/1512.png",
    team: { id: "t-ars", name: "Arsenal", logo: "https://media.api-sports.io/football/teams/42.png" },
    position: "Midfielder",
    marketValue: "EUR 120m",
    stats: { appearances: 28, goals: 6, assists: 5, minutes: 2460, rating: "7.35", yellowCards: 6, redCards: 0 },
  },
  "p-odegaard": {
    id: "p-odegaard",
    name: "Martin Odegaard",
    firstname: "Martin",
    lastname: "Odegaard",
    age: 28,
    nationality: "Norway",
    photo: "https://media.api-sports.io/football/players/1905.png",
    team: { id: "t-ars", name: "Arsenal", logo: "https://media.api-sports.io/football/teams/42.png" },
    position: "Attacking Midfield",
    marketValue: "EUR 110m",
    stats: { appearances: 27, goals: 9, assists: 9, minutes: 2260, rating: "7.44", yellowCards: 3, redCards: 0 },
  },
  "p-kane": {
    id: "p-kane",
    name: "Harry Kane",
    firstname: "Harry",
    lastname: "Kane",
    age: 33,
    nationality: "England",
    photo: "https://media.api-sports.io/football/players/184.png",
    team: { id: "t-bay", name: "Bayern Munich", logo: "https://media.api-sports.io/football/teams/157.png" },
    position: "Striker",
    marketValue: "EUR 100m",
    stats: { appearances: 26, goals: 25, assists: 7, minutes: 2230, rating: "7.81", yellowCards: 2, redCards: 0 },
  },
  "p-musiala": {
    id: "p-musiala",
    name: "Jamal Musiala",
    firstname: "Jamal",
    lastname: "Musiala",
    age: 23,
    nationality: "Germany",
    photo: "https://media.api-sports.io/football/players/120048.png",
    team: { id: "t-bay", name: "Bayern Munich", logo: "https://media.api-sports.io/football/teams/157.png" },
    position: "Attacking Midfield",
    marketValue: "EUR 130m",
    stats: { appearances: 24, goals: 12, assists: 8, minutes: 1910, rating: "7.46", yellowCards: 2, redCards: 0 },
  },
  "p-dembele": {
    id: "p-dembele",
    name: "Ousmane Dembele",
    firstname: "Ousmane",
    lastname: "Dembele",
    age: 29,
    nationality: "France",
    photo: "https://media.api-sports.io/football/players/41124.png",
    team: { id: "t-psg", name: "Paris SG", logo: "https://media.api-sports.io/football/teams/85.png" },
    position: "Winger",
    marketValue: "EUR 60m",
    stats: { appearances: 25, goals: 7, assists: 10, minutes: 1920, rating: "7.24", yellowCards: 3, redCards: 0 },
  },
  "p-hakimi": {
    id: "p-hakimi",
    name: "Achraf Hakimi",
    firstname: "Achraf",
    lastname: "Hakimi",
    age: 28,
    nationality: "Morocco",
    photo: "https://media.api-sports.io/football/players/2256.png",
    team: { id: "t-psg", name: "Paris SG", logo: "https://media.api-sports.io/football/teams/85.png" },
    position: "Right Back",
    marketValue: "EUR 70m",
    stats: { appearances: 27, goals: 5, assists: 9, minutes: 2330, rating: "7.31", yellowCards: 5, redCards: 0 },
  },
  "p-lautaro": {
    id: "p-lautaro",
    name: "Lautaro Martinez",
    firstname: "Lautaro",
    lastname: "Martinez",
    age: 29,
    nationality: "Argentina",
    photo: "https://media.api-sports.io/football/players/1140.png",
    team: { id: "t-int", name: "Inter", logo: "https://media.api-sports.io/football/teams/505.png" },
    position: "Striker",
    marketValue: "EUR 110m",
    stats: { appearances: 27, goals: 20, assists: 4, minutes: 2210, rating: "7.59", yellowCards: 4, redCards: 0 },
  },
  "p-osimhen": {
    id: "p-osimhen",
    name: "Victor Osimhen",
    firstname: "Victor",
    lastname: "Osimhen",
    age: 28,
    nationality: "Nigeria",
    photo: "https://media.api-sports.io/football/players/110596.png",
    team: { id: "t-nap", name: "Napoli", logo: "https://media.api-sports.io/football/teams/492.png" },
    position: "Striker",
    marketValue: "EUR 100m",
    stats: { appearances: 24, goals: 16, assists: 3, minutes: 1970, rating: "7.26", yellowCards: 3, redCards: 0 },
  },
  "p-dybala": {
    id: "p-dybala",
    name: "Paulo Dybala",
    firstname: "Paulo",
    lastname: "Dybala",
    age: 33,
    nationality: "Argentina",
    photo: "https://media.api-sports.io/football/players/446.png",
    team: { id: "t-rom", name: "Roma", logo: "https://media.api-sports.io/football/teams/497.png" },
    position: "Forward",
    marketValue: "EUR 25m",
    stats: { appearances: 23, goals: 10, assists: 6, minutes: 1650, rating: "7.18", yellowCards: 2, redCards: 0 },
  },
  "p-gavi": {
    id: "p-gavi",
    name: "Gavi",
    firstname: "Pablo",
    lastname: "Paez",
    age: 22,
    nationality: "Spain",
    photo: "https://media.api-sports.io/football/players/284484.png",
    team: { id: "t-bar", name: "Barcelona", logo: "https://media.api-sports.io/football/teams/529.png" },
    position: "Midfielder",
    marketValue: "EUR 90m",
    stats: { appearances: 20, goals: 3, assists: 5, minutes: 1420, rating: "7.04", yellowCards: 8, redCards: 1 },
  },
  "p-foden": {
    id: "p-foden",
    name: "Phil Foden",
    firstname: "Phil",
    lastname: "Foden",
    age: 26,
    nationality: "England",
    photo: "https://media.api-sports.io/football/players/1099.png",
    team: { id: "t-mci", name: "Manchester City", logo: "https://media.api-sports.io/football/teams/50.png" },
    position: "Attacking Midfield",
    marketValue: "EUR 130m",
    stats: { appearances: 28, goals: 17, assists: 8, minutes: 2360, rating: "7.67", yellowCards: 2, redCards: 0 },
  },
  "p-saka2": {
    id: "p-saka2",
    name: "Bukayo Saka",
    firstname: "Bukayo",
    lastname: "Saka",
    age: 23,
    nationality: "England",
    photo: "https://media.api-sports.io/football/players/1460.png",
    team: { id: "t-ars", name: "Arsenal", logo: "https://media.api-sports.io/football/teams/42.png" },
    position: "Right Winger",
    marketValue: "EUR 140m",
    stats: { appearances: 26, goals: 12, assists: 8, minutes: 2210, rating: "7.42", yellowCards: 3, redCards: 0 },
  },
};

export function getMockPlayer(id: string): PlayerProfile | null {
  return players[id] ?? null;
}

export function searchMockPlayers(q: string): PlayerProfile[] {
  const needle = q.toLowerCase();
  return Object.values(players).filter((p) =>
    p.name.toLowerCase().includes(needle),
  );
}
